name: Detection_of_Artificially_Ripened_Fruit
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_apps:
  cupertino_icons: ^0.1.2
  tflite: any
  image_picker: 0.6.2+3
  tflite_flutter: ^0.5.0
  sprintf: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - assets/

  fonts:
    - family: Mono
      fonts:
        - asset: fonts/UbuntuMono-Regular.ttf
